apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-todo-app-deployment
  labels:
    app: todo-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mongodb
  template:
    metadata:
      labels:
        app: todo-mongodb
    spec:
      containers:
      - name: todo-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

---
apiVersion: v1
kind: Service
metadata:
  name: todo-mongodb-service
spec:
  selector:
    app: todo-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
